---
title: "main_code"
format: html
editor: visual
---

https://www.unhcr.org/sites/default/files/2023-06/global-trends-report-2022.pdf https://dataviz.unhcr.org/tools/r/

```{r}
library(tidyverse)
library(refugees)
library(tidymodels)

asylum_decisions_new <- asylum_decisions %>% 
                        mutate(acc_rate = (dec_recognized + dec_other) / dec_total) %>%
                        filter(acc_rate >= 0 & acc_rate <= 1)
 
regress_asylum = lm(acc_rate~coo_iso + coa_iso + procedure_type + dec_level + dec_pc, data = asylum_decisions_new)
summary(regress_asylum)

```

```{r}
set.seed(100) # Important!

train_data

ref_split  <- initial_split(asylum_decisions, strata = Class, prop = .9)
ref_train  <- training(alz_split)
ref_test   <- testing(alz_split)

# alz_split

tree_mod %>%
  fit(Class ~ tau + VEGF,
      data = alz_train) %>%
  predict(new_data = alz_test) %>%
  mutate(true_class = alz_test$Class) %>%
  accuracy(truth = true_class,
           estimate = .pred_class)
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
