---
title: "something"
author: "Aarushi Tripathi"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)
library(tidyverse)
library(modeldata)
library(tidymodels)
library(refugees)

```



```{r}
 
# creating data for training and testing
  asy_dec_model <- asylum_decisions %>%
            filter(dec_recognized + dec_other + dec_rejected + dec_closed == dec_total) %>%
            mutate(acceptance_rate_pct = (dec_recognized + dec_other)/dec_total)


  set.seed(100) # Important!

  asylum_split  <- initial_split(asy_dec_model)
  asylum_train  <- training(asylum_split)
  asylum_test   <- testing(asylum_split)
  
  # CV data creation
  asylum_folds <- 
    vfold_cv(asylum_train, v = 10, strata = acceptance_rate_pct, breaks = 5)

  # Initialising model and workflow
  rf_mod <-
    rand_forest() %>%
    set_engine("ranger") %>%
    set_mode("regression")
  
  rf_wf <-
    workflow() %>% 
    add_formula(acceptance_rate_pct ~ coo_iso + coa_iso + procedure_type + dec_level + dec_pc) %>% 
    add_model(rf_mod)

  # Tuning for hyperparameters
  rf_tuner <-
    rand_forest(mtry = tune(),
                min_n = tune()) %>%
    set_engine("ranger") %>%
    set_mode("regression")
  
  
  rf_wf <-
    rf_wf %>%
    update_model(rf_tuner)
  
 # setting rmse method for training 
  set.seed(100) # Important!
  rf_results <-
    rf_wf %>%
    tune_grid(resamples = asylum_folds,
              metrics = metric_set(rmse))

rf_results %>%
  collect_metrics()


```


```{r}
# evaluating best hyperparameters
rf_results %>% 
  show_best(metric = "rmse", n = 5)

```
```{r}
rf_results %>% autoplot()

```
```{r}

# fit final model based on best hyperparameters
asy_best <-
  rf_results %>% 
  select_best(metric = "rmse")

last_rf_workflow <- 
  rf_wf %>%
  finalize_workflow(asy_best)

fitted_workflow <- fit(last_rf_workflow, data = asylum_train)

fitted_workflow %>% summary()


```



```{r}
predictions <- predict(fitted_workflow, new_data = asylum_test)
predictions
```

```{r}
# saving model
saveRDS(fitted_workflow, file = "pred_asylum.rds")
```

